In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer

In [3]:
my_df = pd.DataFrame({"A" : [1, 2, 3, 4, 5],
                      "B" : [1, 1, 3, 3, 4],
                      "C" : [1, 2, 9, np.nan, 20]})
my_df

A  B     C
0  1  1   1.0
1  2  1   2.0
2  3  3   9.0
3  4  3   NaN
4  5  4  20.0

In [5]:
knn_imputer = KNNImputer()
knn_imputer.fit_transform(my_df)

array([[ 1.,  1.,  1.],
       [ 2.,  1.,  2.],
       [ 3.,  3.,  9.],
       [ 4.,  3.,  8.],
       [ 5.,  4., 20.]])

In [7]:
knn_imputer = KNNImputer(n_neighbors=1)
knn_imputer.fit_transform(my_df)

array([[ 1.,  1.,  1.],
       [ 2.,  1.,  2.],
       [ 3.,  3.,  9.],
       [ 4.,  3.,  9.],
       [ 5.,  4., 20.]])

In [9]:
knn_imputer = KNNImputer(n_neighbors=2)
knn_imputer.fit_transform(my_df)

array([[ 1. ,  1. ,  1. ],
       [ 2. ,  1. ,  2. ],
       [ 3. ,  3. ,  9. ],
       [ 4. ,  3. , 14.5],
       [ 5. ,  4. , 20. ]])

In [11]:
knn_imputer = KNNImputer(n_neighbors=2, weights="distance")
knn_imputer.fit_transform(my_df)

array([[ 1.        ,  1.        ,  1.        ],
       [ 2.        ,  1.        ,  2.        ],
       [ 3.        ,  3.        ,  9.        ],
       [ 4.        ,  3.        , 13.55634919],
       [ 5.        ,  4.        , 20.        ]])

In [13]:
my_df1 = pd.DataFrame(knn_imputer.fit_transform(my_df), columns=my_df.columns)
my_df1

A    B          C
0  1.0  1.0   1.000000
1  2.0  1.0   2.000000
2  3.0  3.0   9.000000
3  4.0  3.0  13.556349
4  5.0  4.0  20.000000