In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [2]:
my_df = pd.DataFrame({"A" : [1, 4, 7, 10, 13],
                      "B" : [3, 6, 9, np.nan, 15],
                      "C" : [2, 5, np.nan, 11, np.nan]})
my_df

A     B     C
0   1   3.0   2.0
1   4   6.0   5.0
2   7   9.0   NaN
3  10   NaN  11.0
4  13  15.0   NaN

In [5]:
imputer = SimpleImputer()

imputer.fit(my_df)
imputer.transform(my_df)

array([[ 1.  ,  3.  ,  2.  ],
       [ 4.  ,  6.  ,  5.  ],
       [ 7.  ,  9.  ,  6.  ],
       [10.  ,  8.25, 11.  ],
       [13.  , 15.  ,  6.  ]])

In [7]:
imputer.fit_transform(my_df)

array([[ 1.  ,  3.  ,  2.  ],
       [ 4.  ,  6.  ,  5.  ],
       [ 7.  ,  9.  ,  6.  ],
       [10.  ,  8.25, 11.  ],
       [13.  , 15.  ,  6.  ]])

In [9]:
pd.DataFrame(imputer.fit_transform(my_df), columns=my_df.columns)

A      B     C
0   1.0   3.00   2.0
1   4.0   6.00   5.0
2   7.0   9.00   6.0
3  10.0   8.25  11.0
4  13.0  15.00   6.0

In [11]:
imputer.fit_transform(my_df[["B"]])

array([[ 3.  ],
       [ 6.  ],
       [ 9.  ],
       [ 8.25],
       [15.  ]])

In [13]:
my_df["B"] = imputer.fit_transform(my_df[["B"]])
my_df

A      B     C
0   1   3.00   2.0
1   4   6.00   5.0
2   7   9.00   NaN
3  10   8.25  11.0
4  13  15.00   NaN